server:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  thymeleaf:
    cache: false

mybatis:
  mapperLocations: classpath:mapper/**.xml
  config: mybatis-config.xml
  rows_per_transaction: 500

logging:
  level:
    org:
      springframework:
        security: debug